[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "simbabuild"
authors = [{name = "Luis Ferreira"}]
dynamic = ["version", "description"]

dependencies = [
    "rich",
]

[project.urls]
Home = "https://github.com/ljmf00/simbabuild"
